import { useEffect, useState } from 'react'
import AuthShell, { useAuthPage, ErrorBox, go, styles } from '../../../../components/portal-auth/AuthShell'
import { ROUTES, decideStaff, validateTotp, authErrorKey } from '../../../../lib/portal-auth/flow'

/**
 * /portal/staff/mfa/ — mandatory TOTP for staff.
 *   aal1 + no verified factor → enroll (QR + manual key) → verify code → aal2
 *   aal1 + verified factor    → challenge → verify code → aal2
 * The database independently requires aal2 for every staff capability; this page is the UX for it.
 */
function Mfa() {
  const { t, auth, snapshot, refresh } = useAuthPage()
  const [enrollment, setEnrollment] = useState(null) // { factorId, qrSvg, secret }
  const [code, setCode] = useState('')
  const [errorKey, setErrorKey] = useState(null)
  const [busy, setBusy] = useState(false)
  const d = snapshot ? decideStaff(snapshot) : null

  useEffect(() => {
    if (!d) return
    if (d.screen === 'staff-login') go(`${ROUTES.staffLogin}?next=${encodeURIComponent(ROUTES.staffHome)}`)
    if (d.screen === 'staff-home') go(ROUTES.staffHome)
  }, [d && d.screen]) // eslint-disable-line react-hooks/exhaustive-deps

  async function startEnroll() {
    setBusy(true); setErrorKey(null)
    const r = await auth.enrollTotp()
    if (r.error) setErrorKey(authErrorKey(r.error, 'mfa'))
    else setEnrollment({ factorId: r.factorId, qrSvg: r.qrSvg, secret: r.secret })
    setBusy(false)
  }

  async function verify(e) {
    e.preventDefault()
    const v = validateTotp(code)
    if (v) { setErrorKey(v); return }
    const factorId = enrollment ? enrollment.factorId
      : ((snapshot.session.factors || []).find(f => f.factorType === 'totp' && f.status === 'verified') || {}).id
    setBusy(true); setErrorKey(null)
    const { error } = await auth.verifyTotp(factorId, code.trim())
    setCode('')
    if (error) { setErrorKey(authErrorKey(error, 'mfa')); setBusy(false); return }
    await refresh()
    const next = decideStaff(await auth.getSnapshot())
    if (next.screen === 'staff-home') go(ROUTES.staffHome)
    setBusy(false)
  }

  async function signOut() { await auth.signOut(); go(ROUTES.staffLogin) }

  const enroll = !d || d.screen !== 'mfa-challenge'
  const codeForm = (
    <form className={styles.form} onSubmit={verify} noValidate>
      <label className={styles.label}>
        {t.mfa.code}
        <input className={`${styles.input} ${styles.code}`} inputMode="numeric" autoComplete="one-time-code" maxLength={6}
          value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ''))} aria-describedby="mfa-error"
          aria-invalid={errorKey === 'totp_invalid_format' || errorKey === 'totp_rejected'} />
      </label>
      <ErrorBox errorKey={errorKey} id="mfa-error" />
      <button className={styles.primary} type="submit" disabled={busy}>{busy ? t.working : t.mfa.verify}</button>
    </form>
  )
  return (
    <>
      <h1 className={styles.title}>{enroll ? t.mfa.enrollTitle : t.mfa.challengeTitle}</h1>
      <p className={styles.intro}>{enroll ? t.mfa.enrollIntro : t.mfa.challengeIntro}</p>
      {enroll && !enrollment && (
        <>
          <ErrorBox errorKey={errorKey} id="mfa-error" />
          <button className={styles.primary} type="button" onClick={startEnroll} disabled={busy}>{busy ? t.working : t.mfa.start}</button>
        </>
      )}
      {enroll && enrollment && (
        <>
          <p className={styles.intro}>{t.mfa.scan}</p>
          {/* QR is an SVG data URI generated by the official library for this factor only */}
          <img className={styles.qr} src={enrollment.qrSvg} alt={t.mfa.scan} width={200} height={200} />
          <p className={styles.fine}>{t.mfa.manual}</p>
          <p className={styles.secret}>{enrollment.secret}</p>
          {codeForm}
        </>
      )}
      {!enroll && codeForm}
      <p className={styles.fine}>{t.mfa.lost}</p>
      <button className={styles.secondary} type="button" onClick={signOut}>{t.signOut}</button>
    </>
  )
}

export default function StaffMfaPage() {
  return <AuthShell titleEn="Two-step Verification" area="staff"><Mfa /></AuthShell>
}
