/**
 * AskLinTax — Knowledge Library article index
 *
 * SINGLE SOURCE OF TRUTH for article discovery (Library pages, category pages, search).
 * Every PUBLISHED Knowledge Library article must have exactly one entry here.
 * Never add planned or unpublished articles — every entry must be a real, exported page.
 *
 * `npm run build` runs scripts/validate-articles.js, which fails the build if this
 * index drifts from the real article pages (missing pages, unregistered articles,
 * title / difficulty / read-time mismatches, duplicate ids or paths, bad categories).
 *
 * Fields:
 *   id          Stable identifier. Never change it once published, even if the title or URL changes.
 *   path        Public URL with trailing slash. Must equal the article's real route.
 *   category    Key from lib/categories.js. The path must live under that category's path.
 *   foundation  Foundation 20 number, or null for articles outside Foundation 20.
 *   title       Must match the article's META.title exactly.
 *   summary     Short card/search text (~100–140 characters). Not the SEO meta description.
 *   difficulty  'Beginner' | 'Intermediate' | 'Advanced' — must match META.difficulty.
 *   readMinutes Number — must match META.readTime ("6 min read" → 6).
 *   keywords    Search terms real readers use. Keep it short; no keyword stuffing.
 *
 * Tax year and review date are site-wide and come from lib/tax-config.js — not stored per article.
 */

const ARTICLES = [
  {
    id: 'irs-notice',
    path: '/library/irs/irs-notice/',
    category: 'irs',
    foundation: 1,
    title: 'I received an IRS letter. What do I do?',
    summary: 'Most IRS notices are routine. Learn how to read the letter, identify the notice type, and decide your next step.',
    difficulty: 'Beginner',
    readMinutes: 4,
    keywords: ['IRS letter', 'IRS notice', 'CP notice', 'letter from the IRS', 'IRS scam', 'respond to the IRS'],
  },
  {
    id: 'llc-basics',
    path: '/library/business-formation/llc-basics/',
    category: 'business-formation',
    foundation: 2,
    title: 'What is an LLC, and do I need one?',
    summary: 'What an LLC is, what protection it really gives you, how it is taxed, and how to decide whether you need one.',
    difficulty: 'Beginner',
    readMinutes: 6,
    keywords: ['LLC', 'limited liability company', 'form an LLC', 'single-member LLC', 'sole proprietor', 'liability protection'],
  },
  {
    id: 'llc-vs-scorp',
    path: '/library/business-formation/llc-vs-scorp/',
    category: 'business-formation',
    foundation: 3,
    title: 'LLC vs S-Corp: which is right for your business?',
    summary: 'How LLCs and S-Corps are taxed, with real numbers and the income level where an S-Corp election starts to make sense.',
    difficulty: 'Intermediate',
    readMinutes: 7,
    keywords: ['S-Corp', 'S corporation', 'LLC vs S Corp', 'S-Corp election', 'Form 2553', 'reasonable salary', 'self-employment tax'],
  },
  {
    id: 'new-immigrant',
    path: '/library/individual/new-immigrant/',
    category: 'individual',
    foundation: 4,
    title: 'New to the U.S.? A complete tax guide for new immigrants',
    summary: 'Your first U.S. tax year, step by step: residency status, what income to report, ITIN or SSN, FBAR, and key deadlines.',
    difficulty: 'Beginner',
    readMinutes: 8,
    keywords: ['new immigrant', 'green card', 'first year in the U.S.', 'dual-status', 'worldwide income', 'moving to the U.S.'],
  },
  {
    id: 'tax-residency',
    path: '/library/individual/tax-residency/',
    category: 'individual',
    foundation: 5,
    title: 'Am I a U.S. tax resident?',
    summary: 'Resident or nonresident alien? The Green Card Test and the Substantial Presence Test explained in plain language.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['tax residency', 'resident alien', 'nonresident alien', 'substantial presence test', 'green card test', '183 days', 'F-1', 'H-1B'],
  },
  {
    id: 'do-i-need-to-file',
    path: '/library/individual/do-i-need-to-file/',
    category: 'individual',
    foundation: 6,
    title: 'Do I need to file a U.S. tax return?',
    summary: 'Filing thresholds by filing status, the situations that always require a return, and when it pays to file anyway.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['do I have to file', 'filing requirement', 'filing threshold', 'gross income', 'filing status', 'students'],
  },
  {
    id: 'first-time-filer',
    path: '/library/individual/first-time-filer/',
    category: 'individual',
    foundation: 7,
    title: 'First-time filer in the U.S.: a complete step-by-step guide',
    summary: 'Filing your first U.S. return: what to gather, how to choose a filing method, reading your W-2, and tracking your refund.',
    difficulty: 'Beginner',
    readMinutes: 8,
    keywords: ['first tax return', 'how to file taxes', 'filing for the first time', 'standard deduction', 'tax refund', 'filing deadline'],
  },
  {
    id: 'tax-credit-vs-deduction',
    path: '/library/individual/tax-credit-vs-deduction/',
    category: 'individual',
    foundation: 8,
    title: 'Tax credit vs. tax deduction: what\'s the difference?',
    summary: 'Why a credit and a deduction of the same amount are worth very different things, explained with real numbers.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['tax credit', 'tax deduction', 'refundable credit', 'standard deduction', 'itemize', 'credit vs deduction'],
  },
  {
    id: 'what-is-w2',
    path: '/library/individual/what-is-w2/',
    category: 'individual',
    foundation: 9,
    title: 'What is a W-2 and how do I read it?',
    summary: 'A box-by-box guide to your W-2: why Box 1 may be lower than your salary, what Box 12 codes mean, and fixing errors.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['W-2', 'Form W-2', 'wage and tax statement', 'Box 1', 'Box 12', 'W-2 error'],
  },
  {
    id: 'w2-vs-1099',
    path: '/library/individual/w2-vs-1099/',
    category: 'individual',
    foundation: 10,
    title: 'W-2 vs 1099: what\'s the difference and why it matters',
    summary: 'Employee or contractor? How W-2 and 1099 income are taxed, what 1099 workers can deduct, and what to do if you have both.',
    difficulty: 'Beginner',
    readMinutes: 6,
    keywords: ['1099', '1099-NEC', 'independent contractor', 'employee vs contractor', 'freelancer', 'self-employment tax'],
  },
  {
    id: 'airbnb-tax-guide',
    path: '/library/rental/airbnb-tax-guide/',
    category: 'rental',
    foundation: 11,
    title: 'Airbnb host tax guide: what to report and what to deduct',
    summary: 'What Airbnb income to report, which expenses you can deduct, Schedule E vs Schedule C, and how the 14-day rule fits in.',
    difficulty: 'Intermediate',
    readMinutes: 7,
    keywords: ['Airbnb', 'short-term rental', 'rental income', 'Airbnb deductions', 'Schedule E', 'Schedule C', '1099-K', 'VRBO'],
  },
  {
    id: '14-day-rule',
    path: '/library/rental/14-day-rule/',
    category: 'rental',
    foundation: 12,
    title: 'The 14-day rule: when Airbnb income is completely tax-free',
    summary: 'Rent your home for 14 days or fewer and the income can be tax-free. How the rule works, what counts, and the tradeoffs.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['14-day rule', 'Augusta rule', 'tax-free rental income', 'vacation home', 'personal use days', 'short-term rental'],
  },
  {
    id: 'quarterly-taxes',
    path: '/library/small-business/quarterly-taxes/',
    category: 'small-business',
    foundation: 13,
    title: 'Quarterly estimated taxes: who pays and how to calculate',
    summary: 'Who must pay estimated taxes, the quarterly due dates, how to calculate each payment, and how to avoid underpayment penalties.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['estimated taxes', 'quarterly taxes', 'Form 1040-ES', 'underpayment penalty', 'safe harbor', 'self-employed', 'freelancer'],
  },
  {
    id: 'business-deductions',
    path: '/library/small-business/business-deductions/',
    category: 'small-business',
    foundation: 14,
    title: 'What can I deduct as a small business owner?',
    summary: 'The main Schedule C deductions, including home office, vehicle, equipment, and meals, plus what you cannot deduct.',
    difficulty: 'Intermediate',
    readMinutes: 7,
    keywords: ['business deductions', 'write-offs', 'Schedule C', 'home office deduction', 'mileage', 'business meals', 'ordinary and necessary'],
  },
  {
    id: 'ein',
    path: '/library/business-formation/ein/',
    category: 'business-formation',
    foundation: 15,
    title: 'How to apply for an EIN: a step-by-step guide',
    summary: 'Get a free EIN from the IRS online, step by step: who needs one, what to do without an SSN, and what comes next.',
    difficulty: 'Beginner',
    readMinutes: 4,
    keywords: ['EIN', 'employer identification number', 'tax ID number', 'apply for an EIN', 'Form SS-4', 'EIN without SSN'],
  },
  {
    id: 'cp2000',
    path: '/library/irs/cp2000/',
    category: 'irs',
    foundation: 16,
    title: 'CP2000 notice: what it means and how to respond',
    summary: 'A CP2000 is a mismatch notice, not an audit. What the IRS found, your three response options, and how to resolve it.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['CP2000', 'IRS mismatch', 'underreported income', 'proposed adjustment', 'IRS notice', 'audit'],
  },
  {
    id: 'child-tax-credit',
    path: '/library/individual/child-tax-credit/',
    category: 'individual',
    foundation: 17,
    title: 'Child Tax Credit: who qualifies and how to claim it',
    summary: 'Who counts as a qualifying child, how the income phase-out works, the refundable portion, and how immigrant families can claim it.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['Child Tax Credit', 'CTC', 'qualifying child', 'Additional Child Tax Credit', 'dependents', 'refundable credit'],
  },
  {
    id: 'itin',
    path: '/library/individual/itin/',
    category: 'individual',
    foundation: 18,
    title: 'What is an ITIN and how do I apply?',
    summary: 'Who needs an ITIN, how to apply with Form W-7, how long it takes, and what an ITIN can and cannot be used for.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['ITIN', 'Form W-7', 'individual taxpayer identification number', 'no SSN', 'ITIN renewal', 'acceptance agent'],
  },
  {
    id: 'crypto-tax',
    path: '/library/investment/crypto-tax/',
    category: 'investment',
    foundation: 19,
    title: 'Crypto taxes explained: when is crypto taxable?',
    summary: 'Which crypto transactions are taxable, how to calculate gains and losses, short- vs long-term rates, and what records to keep.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['crypto', 'cryptocurrency', 'bitcoin', 'capital gains', 'staking', 'NFT', 'Form 8949'],
  },
  {
    id: 'fbar',
    path: '/library/investment/fbar/',
    category: 'investment',
    foundation: 20,
    title: 'FBAR: do I need to report my foreign bank accounts?',
    summary: 'Who must file an FBAR, how the $10,000 threshold works, how to file FinCEN Form 114, and how it differs from FATCA.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['FBAR', 'FinCEN 114', 'foreign bank account', 'FATCA', 'Form 8938', 'overseas accounts', 'Taiwan bank account', 'China bank account'],
  },
]

module.exports = { ARTICLES }
