/**
 * AskLinTax — Knowledge Library article index
 *
 * SINGLE SOURCE OF TRUTH for article discovery (Library pages, category pages, search).
 * Every PUBLISHED Knowledge Library article must have exactly one entry here.
 * Never add planned or unpublished articles — every entry must be a real, exported page.
 *
 * `npm run build` runs scripts/validate-articles.js, which fails the build if this
 * index drifts from the real article pages (missing pages, unregistered articles,
 * title / difficulty / read-time mismatches, duplicate ids or paths, bad categories).
 *
 * Fields:
 *   id          Stable identifier. Never change it once published, even if the title or URL changes.
 *   path        Public URL with trailing slash. Must equal the article's real route.
 *   category    Key from lib/categories.js. The path must live under that category's path.
 *   foundation  Foundation 20 number, or null for articles outside Foundation 20.
 *   title       Must match the article's META.title exactly.
 *   summary     Short card/search text (~100–140 characters). Not the SEO meta description.
 *   difficulty  'Beginner' | 'Intermediate' | 'Advanced' — must match META.difficulty.
 *   readMinutes Number — must match META.readTime ("6 min read" → 6).
 *   keywords    Search terms real readers use. Keep it short; no keyword stuffing.
 *   status      Publication status (see "Content status" below).
 *
 * Content status (enforced by scripts/validate-articles.js):
 *   'official-sources-verified'  The publication standard: the guide was checked against the applicable
 *                                official government sources, which its page lists (META.sources) and
 *                                labels "Official Sources Verified" (META.verification). The only
 *                                publishable status — required for every guide.
 *   Drafts are not listed here at all — see lib/drafts.js.
 *
 * Tax year and review date are site-wide and come from lib/tax-config.js — not stored per article.
 */

const ARTICLES = [
  {
    id: 'irs-notice',
    path: '/library/irs/irs-notice/',
    category: 'irs',
    foundation: 1,
    title: 'I received an IRS letter. What do I do?',
    summary: 'Most IRS notices are routine. Learn how to read the letter, identify the notice type, and decide your next step.',
    difficulty: 'Beginner',
    readMinutes: 4,
    keywords: ['IRS letter', 'IRS notice', 'CP notice', 'letter from the IRS', 'IRS scam', 'respond to the IRS'],
    status: 'official-sources-verified',
  },
  {
    id: 'llc-basics',
    path: '/library/business-formation/llc-basics/',
    category: 'business-formation',
    foundation: 2,
    title: 'What is an LLC, and do I need one?',
    summary: 'What an LLC is, what protection it really gives you, how it is taxed, and how to decide whether you need one.',
    difficulty: 'Beginner',
    readMinutes: 6,
    keywords: ['LLC', 'limited liability company', 'form an LLC', 'single-member LLC', 'sole proprietor', 'liability protection'],
    status: 'official-sources-verified',
  },
  {
    id: 'llc-vs-scorp',
    path: '/library/business-formation/llc-vs-scorp/',
    category: 'business-formation',
    foundation: 3,
    title: 'LLC vs S-Corp: which is right for your business?',
    summary: 'How LLCs and S-Corps are taxed, with real numbers and the income level where an S-Corp election starts to make sense.',
    difficulty: 'Intermediate',
    readMinutes: 7,
    keywords: ['S-Corp', 'S corporation', 'LLC vs S Corp', 'S-Corp election', 'Form 2553', 'reasonable salary', 'self-employment tax'],
    status: 'official-sources-verified',
  },
  {
    id: 'new-immigrant',
    path: '/library/individual/new-immigrant/',
    category: 'individual',
    foundation: 4,
    title: 'New to the U.S.? A complete tax guide for new immigrants',
    summary: 'Your first U.S. tax year, step by step: residency status, what income to report, ITIN or SSN, FBAR, and key deadlines.',
    difficulty: 'Beginner',
    readMinutes: 8,
    keywords: ['new immigrant', 'green card', 'first year in the U.S.', 'dual-status', 'worldwide income', 'moving to the U.S.'],
    status: 'official-sources-verified',
  },
  {
    id: 'tax-residency',
    path: '/library/individual/tax-residency/',
    category: 'individual',
    foundation: 5,
    title: 'Am I a U.S. tax resident?',
    summary: 'Resident or nonresident alien? The Green Card Test and the Substantial Presence Test explained in plain language.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['tax residency', 'resident alien', 'nonresident alien', 'substantial presence test', 'green card test', '183 days', 'F-1', 'H-1B'],
    status: 'official-sources-verified',
  },
  {
    id: 'do-i-need-to-file',
    path: '/library/individual/do-i-need-to-file/',
    category: 'individual',
    foundation: 6,
    title: 'Do I need to file a U.S. tax return?',
    summary: 'Filing thresholds by filing status, the situations that always require a return, and when it pays to file anyway.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['do I have to file', 'filing requirement', 'filing threshold', 'gross income', 'filing status', 'students'],
    status: 'official-sources-verified',
  },
  {
    id: 'first-time-filer',
    path: '/library/individual/first-time-filer/',
    category: 'individual',
    foundation: 7,
    title: 'First-time filer in the U.S.: a complete step-by-step guide',
    summary: 'Filing your first U.S. return: what to gather, how to choose a filing method, reading your W-2, and tracking your refund.',
    difficulty: 'Beginner',
    readMinutes: 8,
    keywords: ['first tax return', 'how to file taxes', 'filing for the first time', 'standard deduction', 'tax refund', 'filing deadline'],
    status: 'official-sources-verified',
  },
  {
    id: 'tax-credit-vs-deduction',
    path: '/library/individual/tax-credit-vs-deduction/',
    category: 'individual',
    foundation: 8,
    title: 'Tax credit vs. tax deduction: what\'s the difference?',
    summary: 'Why a credit and a deduction of the same amount are worth very different things, explained with real numbers.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['tax credit', 'tax deduction', 'refundable credit', 'standard deduction', 'itemize', 'credit vs deduction'],
    status: 'official-sources-verified',
  },
  {
    id: 'what-is-w2',
    path: '/library/individual/what-is-w2/',
    category: 'individual',
    foundation: 9,
    title: 'What is a W-2 and how do I read it?',
    summary: 'A box-by-box guide to your W-2: why Box 1 may be lower than your salary, what Box 12 codes mean, and fixing errors.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['W-2', 'Form W-2', 'wage and tax statement', 'Box 1', 'Box 12', 'W-2 error'],
    status: 'official-sources-verified',
  },
  {
    id: 'w2-vs-1099',
    path: '/library/individual/w2-vs-1099/',
    category: 'individual',
    foundation: 10,
    title: 'W-2 vs 1099: what\'s the difference and why it matters',
    summary: 'Employee or contractor? How W-2 and 1099 income are taxed, what 1099 workers can deduct, and what to do if you have both.',
    difficulty: 'Beginner',
    readMinutes: 6,
    keywords: ['1099', '1099-NEC', 'independent contractor', 'employee vs contractor', 'freelancer', 'self-employment tax'],
    status: 'official-sources-verified',
  },
  {
    id: 'airbnb-tax-guide',
    path: '/library/rental/airbnb-tax-guide/',
    category: 'rental',
    foundation: 11,
    title: 'Airbnb host tax guide: what to report and what to deduct',
    summary: 'What Airbnb income to report, which expenses you can deduct, Schedule E vs Schedule C, and how the 14-day rule fits in.',
    difficulty: 'Intermediate',
    readMinutes: 7,
    keywords: ['Airbnb', 'short-term rental', 'rental income', 'Airbnb deductions', 'Schedule E', 'Schedule C', '1099-K', 'VRBO'],
    status: 'official-sources-verified',
  },
  {
    id: '14-day-rule',
    path: '/library/rental/14-day-rule/',
    category: 'rental',
    foundation: 12,
    title: 'The 14-day rule: when Airbnb income is completely tax-free',
    summary: 'Rent your home for 14 days or fewer and the income can be tax-free. How the rule works, what counts, and the tradeoffs.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['14-day rule', 'Augusta rule', 'tax-free rental income', 'vacation home', 'personal use days', 'short-term rental'],
    status: 'official-sources-verified',
  },
  {
    id: 'quarterly-taxes',
    path: '/library/small-business/quarterly-taxes/',
    category: 'small-business',
    foundation: 13,
    title: 'Quarterly estimated taxes: who pays and how to calculate',
    summary: 'Who must pay estimated taxes, the quarterly due dates, how to calculate each payment, and how to avoid underpayment penalties.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['estimated taxes', 'quarterly taxes', 'Form 1040-ES', 'underpayment penalty', 'safe harbor', 'self-employed', 'freelancer'],
    status: 'official-sources-verified',
  },
  {
    id: 'business-deductions',
    path: '/library/small-business/business-deductions/',
    category: 'small-business',
    foundation: 14,
    title: 'What can I deduct as a small business owner?',
    summary: 'The main Schedule C deductions, including home office, vehicle, equipment, and meals, plus what you cannot deduct.',
    difficulty: 'Intermediate',
    readMinutes: 7,
    keywords: ['business deductions', 'write-offs', 'Schedule C', 'home office deduction', 'mileage', 'business meals', 'ordinary and necessary'],
    status: 'official-sources-verified',
  },
  {
    id: 'ein',
    path: '/library/business-formation/ein/',
    category: 'business-formation',
    foundation: 15,
    title: 'How to apply for an EIN: a step-by-step guide',
    summary: 'Get a free EIN from the IRS online, step by step: who needs one, what to do without an SSN, and what comes next.',
    difficulty: 'Beginner',
    readMinutes: 4,
    keywords: ['EIN', 'employer identification number', 'tax ID number', 'apply for an EIN', 'Form SS-4', 'EIN without SSN'],
    status: 'official-sources-verified',
  },
  {
    id: 'cp2000',
    path: '/library/irs/cp2000/',
    category: 'irs',
    foundation: 16,
    title: 'CP2000 notice: what it means and how to respond',
    summary: 'A CP2000 is a mismatch notice, not an audit. What the IRS found, your three response options, and how to resolve it.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['CP2000', 'IRS mismatch', 'underreported income', 'proposed adjustment', 'IRS notice', 'audit'],
    status: 'official-sources-verified',
  },
  {
    id: 'child-tax-credit',
    path: '/library/individual/child-tax-credit/',
    category: 'individual',
    foundation: 17,
    title: 'Child Tax Credit: who qualifies and how to claim it',
    summary: 'Who counts as a qualifying child, how the income phase-out works, the refundable portion, and how immigrant families can claim it.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['Child Tax Credit', 'CTC', 'qualifying child', 'Additional Child Tax Credit', 'dependents', 'refundable credit'],
    status: 'official-sources-verified',
  },
  {
    id: 'itin',
    path: '/library/individual/itin/',
    category: 'individual',
    foundation: 18,
    title: 'What is an ITIN and how do I apply?',
    summary: 'Who needs an ITIN, how to apply with Form W-7, how long it takes, and what an ITIN can and cannot be used for.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['ITIN', 'Form W-7', 'individual taxpayer identification number', 'no SSN', 'ITIN renewal', 'acceptance agent'],
    status: 'official-sources-verified',
  },
  {
    id: 'crypto-tax',
    path: '/library/investment/crypto-tax/',
    category: 'investment',
    foundation: 19,
    title: 'Crypto taxes explained: when is crypto taxable?',
    summary: 'Which crypto transactions are taxable, how to calculate gains and losses, short- vs long-term rates, and what records to keep.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['crypto', 'cryptocurrency', 'bitcoin', 'capital gains', 'staking', 'NFT', 'Form 8949'],
    status: 'official-sources-verified',
  },
  {
    id: 'fbar',
    path: '/library/investment/fbar/',
    category: 'investment',
    foundation: 20,
    title: 'FBAR: do I need to report my foreign bank accounts?',
    summary: 'Who must file an FBAR, how the $10,000 threshold works, how to file FinCEN Form 114, and how it differs from FATCA.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['FBAR', 'FinCEN 114', 'foreign bank account', 'FATCA', 'Form 8938', 'overseas accounts', 'Taiwan bank account', 'China bank account'],
    status: 'official-sources-verified',
  },

  // ── Batch 1: New to the U.S. & international tax (Official Sources Verified) ──
  {
    id: 'foreign-gifts',
    path: '/library/investment/foreign-gifts/',
    category: 'investment',
    foundation: 21,
    title: 'Foreign gifts: is money from parents overseas taxable?',
    summary: 'Money from parents abroad is generally not taxable income — but related gifts over $100,000 in a year must be reported on Form 3520.',
    difficulty: 'Beginner',
    readMinutes: 6,
    keywords: ['foreign gift', 'gift from parents', 'money from parents overseas', 'gift from Taiwan', 'wire transfer from abroad', 'inheritance from abroad', 'Form 3520', 'is a gift taxable'],
    status: 'official-sources-verified',
  },
  {
    id: 'form-3520',
    path: '/library/investment/form-3520/',
    category: 'investment',
    foundation: 22,
    title: 'Form 3520: reporting large foreign gifts',
    summary: 'Who must file Form 3520 Part IV, the $100,000 threshold, due dates and extensions, where to mail it, and the 5%-per-month penalty.',
    difficulty: 'Intermediate',
    readMinutes: 5,
    keywords: ['Form 3520', 'Part IV', 'foreign gift reporting', 'foreign inheritance', 'bequest from abroad', '3520 penalty', 'large gift from abroad'],
    status: 'official-sources-verified',
  },
  {
    id: 'fbar-vs-form-8938',
    path: '/library/investment/fbar-vs-form-8938/',
    category: 'investment',
    foundation: 23,
    title: 'FBAR vs. Form 8938: what\'s the difference?',
    summary: 'FBAR and Form 8938 are separate requirements. Compare thresholds, who files, which assets count, deadlines, and where each is filed.',
    difficulty: 'Intermediate',
    readMinutes: 5,
    keywords: ['FBAR vs 8938', 'Form 8938', 'FATCA', 'specified foreign financial assets', 'FinCEN 114', 'foreign assets', 'foreign accounts'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-bank-account',
    path: '/library/investment/foreign-bank-account/',
    category: 'investment',
    foundation: 24,
    title: 'Do I need to report a Taiwan or foreign bank account?',
    summary: 'A foreign account raises three separate questions: income tax on interest, the FBAR, and Form 8938. A step-by-step check with an example.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['Taiwan bank account', 'foreign bank account', 'report foreign account', 'interest from foreign bank', 'Schedule B foreign account', 'joint account with parents', 'overseas account'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-property',
    path: '/library/investment/foreign-property/',
    category: 'investment',
    foundation: 25,
    title: 'Foreign property: what U.S. taxpayers need to know',
    summary: 'Owning a home abroad is not reported on the FBAR or Form 8938 — but rent, sale gains, and large inheritances have U.S. tax rules.',
    difficulty: 'Intermediate',
    readMinutes: 5,
    keywords: ['foreign property', 'house in Taiwan', 'foreign real estate', 'sell property abroad', 'inherit property abroad', 'foreign property tax', 'overseas home'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-rental-property',
    path: '/library/rental/foreign-rental-property/',
    category: 'rental',
    foundation: 26,
    title: 'Foreign rental property and U.S. taxes',
    summary: 'How U.S. residents report rent from property abroad: Schedule E, expenses, 30-year ADS depreciation, currency, and the foreign tax credit.',
    difficulty: 'Intermediate',
    readMinutes: 5,
    keywords: ['foreign rental property', 'rent out apartment in Taiwan', 'foreign rental income', 'overseas rental', 'ADS depreciation', 'Schedule E foreign property'],
    status: 'official-sources-verified',
  },
  {
    id: 'nonresident-spouse',
    path: '/library/individual/nonresident-spouse/',
    category: 'individual',
    foundation: 27,
    title: 'Nonresident spouse: can we file jointly?',
    summary: 'Married to someone who is not a U.S. resident? Compare filing separately, head of household, and electing to treat your spouse as a resident.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['nonresident spouse', 'nonresident alien spouse', 'spouse in Taiwan', 'file jointly with foreign spouse', 'treat spouse as resident', 'married filing jointly'],
    status: 'official-sources-verified',
  },
  {
    id: 'dual-status',
    path: '/library/individual/dual-status/',
    category: 'individual',
    foundation: 28,
    title: 'Dual-status tax returns: your year of arrival or departure',
    summary: 'Resident for part of the year? How dual-status returns work: residency start dates, what income is taxed, restrictions, and how to file.',
    difficulty: 'Advanced',
    readMinutes: 5,
    keywords: ['dual-status', 'dual status alien', 'year of arrival', 'year of departure', 'part-year resident', 'dual-status return', 'Form 1040-NR statement'],
    status: 'official-sources-verified',
  },
  {
    id: 'substantial-presence-test',
    path: '/library/individual/substantial-presence-test/',
    category: 'individual',
    foundation: 29,
    title: 'Substantial Presence Test explained: how to count your days',
    summary: 'The 31-day and 183-day formula, which days count, exempt students and teachers, Form 8843, and the closer connection exception.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['substantial presence test', '183 days', 'day count', 'days in the U.S.', 'Form 8843', 'Form 8840', 'closer connection', 'exempt individual', 'parents visiting'],
    status: 'official-sources-verified',
  },
  {
    id: 'worldwide-income',
    path: '/library/individual/worldwide-income/',
    category: 'individual',
    foundation: 30,
    title: 'Foreign income: do U.S. tax residents report worldwide income?',
    summary: 'U.S. residents are taxed on income from everywhere. What counts, what does not, and how the foreign tax credit and FEIE work.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['worldwide income', 'foreign income', 'Taiwan income', 'income from abroad', 'foreign tax credit', 'foreign earned income exclusion', 'FEIE', 'report foreign salary'],
    status: 'official-sources-verified',
  },

  // ── Batch 1 (content depth): Foreign gifts & Form 3520 deep dives (Official Sources Verified) ──
  {
    id: 'foreign-gift-over-100000',
    path: '/library/investment/foreign-gift-over-100000/',
    category: 'investment',
    foundation: 31,
    title: 'Parents overseas sent me more than $100,000 — do I need Form 3520?',
    summary: 'Over $100,000 from nonresident parents in a year? Why it is generally not taxable but must be reported on Form 3520 Part IV.',
    difficulty: 'Beginner',
    readMinutes: 7,
    keywords: ['more than $100,000 from parents', '100000 gift', 'large gift from parents', 'parents abroad sent money', 'do I need Form 3520', 'gift over 100k'],
    status: 'official-sources-verified',
  },
  {
    id: 'form-3520-multiple-gifts',
    path: '/library/investment/form-3520-multiple-gifts/',
    category: 'investment',
    foundation: 32,
    title: 'Multiple foreign gifts: how does the $100,000 Form 3520 threshold work?',
    summary: 'Several transfers, two parents, or relatives abroad: how gifts are added up for the Form 3520 threshold, and why splitting does not help.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['multiple gifts', 'aggregate gifts', 'related donors', 'split transfers', 'monthly transfers from parents', 'gifts from both parents', 'nominee intermediary'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-gift-home-down-payment',
    path: '/library/investment/foreign-gift-home-down-payment/',
    category: 'investment',
    foundation: 33,
    title: 'Parents overseas helped with my U.S. home down payment — is it a foreign gift?',
    summary: 'Money from parents abroad for a U.S. home: gift, loan, or co-ownership, when Form 3520 applies, and the records lenders and the IRS want.',
    difficulty: 'Beginner',
    readMinutes: 6,
    keywords: ['down payment', 'home purchase gift', 'buy a house with parents money', 'gift letter', 'escrow', 'source of funds', 'mortgage'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-gift-tuition-paid-directly',
    path: '/library/investment/foreign-gift-tuition-paid-directly/',
    category: 'investment',
    foundation: 34,
    title: 'My parents paid my tuition directly — do I report a foreign gift?',
    summary: 'Tuition paid straight to a school is not a foreign gift for Form 3520. Money sent to you, housing, and books are. The narrow exception explained.',
    difficulty: 'Beginner',
    readMinutes: 5,
    keywords: ['tuition', 'tuition paid directly', 'college tuition from parents', 'international student', 'medical payments', 'qualified transfer', 'room and board'],
    status: 'official-sources-verified',
  },
  {
    id: 'transfer-own-money-to-us',
    path: '/library/investment/transfer-own-money-to-us/',
    category: 'investment',
    foundation: 35,
    title: 'I transferred my own money from overseas to the U.S. — is it taxable?',
    summary: 'Moving your own savings to the U.S. is not income by itself. What matters is where the money came from and your foreign account reporting.',
    difficulty: 'Beginner',
    readMinutes: 6,
    keywords: ['transfer my own money', 'move savings to the U.S.', 'wire money from Taiwan', 'bring money to America', 'own funds', 'close foreign account', 'international transfer'],
    status: 'official-sources-verified',
  },
  {
    id: 'sold-foreign-property-transfer',
    path: '/library/investment/sold-foreign-property-transfer/',
    category: 'investment',
    foundation: 36,
    title: 'I sold property overseas and moved the money to the U.S. — what must I report?',
    summary: 'The sale and the transfer are separate. How U.S. residents report a foreign property sale: basis, currency, foreign tax credit, and FBAR.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['sold property abroad', 'sold house in Taiwan', 'foreign property sale', 'sale proceeds', 'capital gain foreign property', 'move sale money', 'sold apartment overseas'],
    status: 'official-sources-verified',
  },
  {
    id: 'late-form-3520',
    path: '/library/investment/late-form-3520/',
    category: 'investment',
    foundation: 37,
    title: 'I filed Form 3520 late — what should I do now?',
    summary: 'Missed Form 3520 for a gift or inheritance from abroad? The penalty, reasonable cause, and the IRS procedure for late information returns.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['late Form 3520', 'missed Form 3520', 'forgot to file 3520', 'reasonable cause', 'delinquent international information return', 'penalty abatement', 'penalty notice'],
    status: 'official-sources-verified',
  },
  {
    id: 'form-3520-married-couples',
    path: '/library/investment/form-3520-married-couples/',
    category: 'investment',
    foundation: 38,
    title: 'My spouse and I received money from overseas parents — how does Form 3520 work?',
    summary: 'Gifts from parents abroad to a married couple: why it matters who received each gift, joint accounts, nonresident spouses, and joint returns.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['married couple gift', 'spouse', 'husband and wife', 'joint account gift', 'in-laws', 'parents-in-law', 'joint Form 3520'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-gift-vs-inheritance',
    path: '/library/investment/foreign-gift-vs-inheritance/',
    category: 'investment',
    foundation: 39,
    title: 'Foreign gift vs. foreign inheritance: what U.S. taxpayers need to report',
    summary: 'Gifts and inheritances from family abroad compared: Form 3520 reporting, what is still taxable, and how basis differs when you sell.',
    difficulty: 'Intermediate',
    readMinutes: 6,
    keywords: ['inheritance', 'bequest', 'foreign estate', 'gift vs inheritance', 'inherited property basis', 'step-up in basis', 'inherited from parents abroad'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-gift-vs-foreign-trust',
    path: '/library/investment/foreign-gift-vs-foreign-trust/',
    category: 'investment',
    foundation: 40,
    title: 'Foreign gift from your parents vs. foreign trust distribution — why the difference matters',
    summary: 'A gift from a parent abroad and a foreign trust distribution are different: Form 3520 Part IV vs. Part III, thresholds, penalties, and tax.',
    difficulty: 'Advanced',
    readMinutes: 6,
    keywords: ['foreign trust', 'trust distribution', 'Part III', 'family trust abroad', 'beneficiary statement', 'grantor trust', 'nongrantor trust'],
    status: 'official-sources-verified',
  },

  // ── Batch 2 (content depth): FBAR, Form 8938 & foreign accounts (Official Sources Verified) ──
  {
    id: 'fbar-10000-rule',
    path: '/library/investment/fbar-10000-rule/',
    category: 'investment',
    foundation: 41,
    title: 'Do I need to file an FBAR? How the $10,000 rule really works',
    summary: 'The FBAR $10,000 test adds up all your foreign accounts at any time in the year — not per account, not year-end. Examples.',
    difficulty: 'Beginner',
    readMinutes: 4,
    keywords: ['$10,000 rule', 'aggregate', 'combined balance', 'multiple foreign accounts', 'two Taiwan accounts', 'per account', 'at any time', 'foreign bank account over $10,000', 'do I need to report'],
    status: 'official-sources-verified',
  },
  {
    id: 'fbar-maximum-account-value',
    path: '/library/investment/fbar-maximum-account-value/',
    category: 'investment',
    foundation: 42,
    title: 'What is the maximum value of a foreign account for FBAR?',
    summary: 'How to figure each account\'s FBAR maximum value: highest balance in the year, statements, year-end Treasury rate, rounding.',
    difficulty: 'Intermediate',
    readMinutes: 4,
    keywords: ['maximum account value', 'maximum value', 'highest balance', 'exchange rate', 'Treasury rate', 'FBAR value', 'rounding'],
    status: 'official-sources-verified',
  },
  {
    id: 'new-us-resident-foreign-accounts',
    path: '/library/investment/new-us-resident-foreign-accounts/',
    category: 'investment',
    foundation: 43,
    title: 'I just moved to the U.S. — do I need to report my foreign bank accounts?',
    summary: 'First U.S. year with accounts abroad: when residency starts, FBAR and Form 8938 periods, thresholds, and account income.',
    difficulty: 'Intermediate',
    readMinutes: 5,
    keywords: ['just moved to the U.S.', 'first year', 'year of arrival', 'new resident', 'residency starting date', 'moved this year', 'arrived'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-account-no-interest',
    path: '/library/investment/foreign-account-no-interest/',
    category: 'investment',
    foundation: 44,
    title: 'My foreign bank account earned no interest — do I still need to report it?',
    summary: 'No interest does not mean no FBAR. Account reporting depends on value; income reporting depends on what was earned.',
    difficulty: 'Beginner',
    readMinutes: 4,
    keywords: ['no interest', 'zero interest', 'dormant account', 'no income', 'checking account', 'account reporting vs income'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-time-deposit-cd',
    path: '/library/investment/foreign-time-deposit-cd/',
    category: 'investment',
    foundation: 45,
    title: 'Foreign CDs and time deposits: do they go on FBAR or Form 8938?',
    summary: 'A time deposit or CD at a foreign bank is a foreign financial account: FBAR, Form 8938, maximum value, and interest income.',
    difficulty: 'Beginner',
    readMinutes: 4,
    keywords: ['CD', 'certificate of deposit', 'time deposit', 'fixed deposit', 'Taiwan CD', 'rollover', 'term deposit'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-brokerage-account',
    path: '/library/investment/foreign-brokerage-account/',
    category: 'investment',
    foundation: 46,
    title: 'Foreign brokerage accounts and stocks: what goes on FBAR and Form 8938?',
    summary: 'Foreign brokerage accounts vs. foreign stock held directly: what is reported on the FBAR, what on Form 8938, and what is not.',
    difficulty: 'Intermediate',
    readMinutes: 4,
    keywords: ['brokerage account', 'securities account', 'foreign stock', 'Taiwan stocks', 'shares', 'investment account', 'stock certificate'],
    status: 'official-sources-verified',
  },
  {
    id: 'foreign-life-insurance-cash-value',
    path: '/library/investment/foreign-life-insurance-cash-value/',
    category: 'investment',
    foundation: 47,
    title: 'Foreign life insurance with cash value: is it reportable?',
    summary: 'Foreign life insurance or annuity contracts with a cash value are reportable on the FBAR and Form 8938. What counts and what does not.',
    difficulty: 'Intermediate',
    readMinutes: 4,
    keywords: ['life insurance', 'cash value', 'surrender value', 'savings insurance', 'annuity', 'whole life', 'insurance policy'],
    status: 'official-sources-verified',
  },
  {
    id: 'late-fbar',
    path: '/library/investment/late-fbar/',
    category: 'investment',
    foundation: 48,
    title: 'I forgot to file an FBAR — what should I do?',
    summary: 'Missed an FBAR? IRS delinquent FBAR procedures, streamlined procedures, and voluntary disclosure, and why unreported income matters.',
    difficulty: 'Intermediate',
    readMinutes: 4,
    keywords: ['late FBAR', 'forgot FBAR', 'missed FBAR', 'delinquent FBAR', 'streamlined', 'voluntary disclosure', 'FBAR penalty'],
    status: 'official-sources-verified',
  },
  {
    id: 'joint-foreign-account-fbar',
    path: '/library/investment/joint-foreign-account-fbar/',
    category: 'investment',
    foundation: 49,
    title: 'Joint foreign accounts: how do married couples file FBAR?',
    summary: 'Each joint owner reports the full value of a joint foreign account. When one spouse can file for both using FinCEN Form 114a.',
    difficulty: 'Intermediate',
    readMinutes: 4,
    keywords: ['joint account', 'jointly owned', 'married couple FBAR', 'spouse', 'wife', 'husband', 'Form 114a'],
    status: 'official-sources-verified',
  },
  {
    id: 'pre-immigration-savings',
    path: '/library/investment/pre-immigration-savings/',
    category: 'investment',
    foundation: 50,
    title: 'I had this money before moving to America — does that change FBAR or Form 8938?',
    summary: 'Savings from before you immigrated are generally not taxed again, but the foreign accounts holding them can still be reportable.',
    difficulty: 'Beginner',
    readMinutes: 4,
    keywords: ['before moving', 'before I came', 'pre-immigration', 'old savings', 'money from before', 'savings before immigrating', 'before green card'],
    status: 'official-sources-verified',
  },
]

module.exports = { ARTICLES }
