/** AskLinTax Client Portal — Phase 2B-4 auth UI strings (English + Traditional Chinese). */

const STRINGS = {
  en: {
    portalLabel: 'Client Portal', staffLabel: 'Staff Portal', langLabel: 'Language', backHome: 'AskLinTax home',
    unavailable: 'Portal sign-in is not available yet. This page is a preview of the sign-in flow.',
    signOut: 'Sign out', signedOut: 'You have been signed out.', working: 'Please wait…',
    email: 'Email address', password: 'Password',
    errors: {
      not_configured: 'Portal sign-in is not available yet.',
      signin_failed: 'The email address or password is incorrect, or the account is not active.',
      rate_limited: 'Too many attempts. Please wait a few minutes and try again.',
      network: 'We could not reach the sign-in service. Check your connection and try again.',
      email_invalid: 'Enter a valid email address.',
      password_too_short: 'Use at least 12 characters.',
      password_too_long: 'Use at most 128 characters.',
      password_mismatch: 'The two passwords do not match.',
      password_rejected: 'This password cannot be used. Please choose a different one.',
      link_expired: 'This link has expired or was already used. Request a new one.',
      totp_invalid_format: 'Enter the 6-digit code from your authenticator app.',
      totp_rejected: 'That code did not work. Check your authenticator app and try again.',
      generic: 'Something went wrong. Please try again.',
    },
    login: {
      title: 'Sign in to your portal',
      intro: 'Sign in with the email address your AskLinTax invitation was sent to.',
      submit: 'Sign in', forgot: 'Forgot your password?',
      noAccount: 'Portal accounts are by invitation. If you are a client and need access, contact AskLinTax.',
      staffLink: 'AskLinTax staff sign-in',
    },
    staffLogin: {
      title: 'Staff sign-in',
      intro: 'For AskLinTax staff only. A second step with your authenticator app is always required.',
      submit: 'Continue', clientLink: 'Client sign-in',
    },
    forgot: {
      title: 'Reset your password',
      intro: 'Enter your email address. If it belongs to a portal account, we will send a reset link.',
      submit: 'Send reset link',
      sent: 'If that email address belongs to a portal account, a reset link is on its way. The link expires after a short time.',
      back: 'Back to sign-in',
    },
    reset: {
      title: 'Choose a new password', inviteTitle: 'Set up your password',
      inviteIntro: 'Welcome to the AskLinTax portal. Choose a password of at least 12 characters, then sign in.',
      intro: 'Use at least 12 characters. A longer passphrase is easier to remember and harder to guess.',
      newPassword: 'New password', confirm: 'Confirm new password', submit: 'Save password',
      done: 'Your password has been saved. Please sign in again.', toLogin: 'Go to sign-in',
      noSession: 'Open this page from the link in your email. Links expire after a short time.',
      account: 'Account:',
      notYou: 'Not your account? Do not set a password — sign out and contact AskLinTax.',
    },
    callback: { checking: 'Checking your link…', error: 'This link is invalid or has expired.', toForgot: 'Request a new link' },
    mfa: {
      enrollTitle: 'Set up two-step verification',
      enrollIntro: 'Staff accounts must use an authenticator app (for example Google Authenticator, Microsoft Authenticator or 1Password).',
      scan: 'Scan this QR code with your authenticator app.',
      manual: 'Or enter this key manually:',
      start: 'Start setup',
      challengeTitle: 'Two-step verification',
      challengeIntro: 'Enter the current 6-digit code from your authenticator app.',
      code: '6-digit code', verify: 'Verify',
      lost: 'Lost access to your authenticator? Ask your AskLinTax CPA administrator to reset your two-step verification. Recovery is never done by email alone.',
    },
    clientHome: {
      title: 'You are signed in',
      body: 'Your secure client portal will be connected in a later phase. No tax information is shown here yet.',
    },
    staffHome: {
      title: 'Staff session verified',
      body: 'Two-step verification is complete for this session. Staff tools will be connected in a later phase.',
      note: 'This page only reflects your sign-in state. Access to any client data is decided by the portal database, not by this page.',
    },
  },
  'zh-tw': {
    portalLabel: '客戶入口', staffLabel: '員工入口', langLabel: '語言', backHome: 'AskLinTax 首頁',
    unavailable: '入口登入功能尚未開放。此頁面為登入流程預覽。',
    signOut: '登出', signedOut: '你已登出。', working: '請稍候…',
    email: '電子郵件', password: '密碼',
    errors: {
      not_configured: '入口登入功能尚未開放。',
      signin_failed: '電子郵件或密碼不正確，或帳戶尚未啟用。',
      rate_limited: '嘗試次數過多。請稍候幾分鐘再試。',
      network: '無法連線到登入服務。請檢查網路連線後再試。',
      email_invalid: '請輸入有效的電子郵件。',
      password_too_short: '密碼至少需要 12 個字元。',
      password_too_long: '密碼最多 128 個字元。',
      password_mismatch: '兩次輸入的密碼不一致。',
      password_rejected: '無法使用這個密碼，請改用其他密碼。',
      link_expired: '此連結已過期或已使用過。請重新申請。',
      totp_invalid_format: '請輸入驗證器 App 上的 6 位數驗證碼。',
      totp_rejected: '驗證碼不正確。請確認驗證器 App 後再試。',
      generic: '發生錯誤，請再試一次。',
    },
    login: {
      title: '登入客戶入口',
      intro: '請使用收到 AskLinTax 邀請的電子郵件登入。',
      submit: '登入', forgot: '忘記密碼？',
      noAccount: '入口帳戶採邀請制。如果你是客戶並需要使用入口，請與 AskLinTax 聯絡。',
      staffLink: 'AskLinTax 員工登入',
    },
    staffLogin: {
      title: '員工登入',
      intro: '僅限 AskLinTax 員工。每次都必須以驗證器 App 完成第二步驗證。',
      submit: '繼續', clientLink: '客戶登入',
    },
    forgot: {
      title: '重設密碼',
      intro: '請輸入電子郵件。如果這是入口帳戶，我們會寄出重設連結。',
      submit: '寄出重設連結',
      sent: '如果這個電子郵件屬於入口帳戶，重設連結已寄出。連結會在短時間後失效。',
      back: '返回登入',
    },
    reset: {
      title: '設定新密碼', inviteTitle: '設定你的密碼',
      inviteIntro: '歡迎使用 AskLinTax 入口。請設定至少 12 個字元的密碼，然後登入。',
      intro: '密碼至少 12 個字元。較長的通關語句更容易記住，也更難被猜到。',
      newPassword: '新密碼', confirm: '再次輸入新密碼', submit: '儲存密碼',
      done: '密碼已儲存。請重新登入。', toLogin: '前往登入',
      noSession: '請從電子郵件中的連結開啟此頁面。連結會在短時間後失效。',
      account: '帳戶：',
      notYou: '這不是你的帳戶？請不要設定密碼，先登出並與 AskLinTax 聯絡。',
    },
    callback: { checking: '正在確認連結…', error: '此連結無效或已過期。', toForgot: '重新申請連結' },
    mfa: {
      enrollTitle: '設定兩步驟驗證',
      enrollIntro: '員工帳戶必須使用驗證器 App（例如 Google Authenticator、Microsoft Authenticator 或 1Password）。',
      scan: '請用驗證器 App 掃描這個 QR Code。',
      manual: '或手動輸入這組金鑰：',
      start: '開始設定',
      challengeTitle: '兩步驟驗證',
      challengeIntro: '請輸入驗證器 App 上目前的 6 位數驗證碼。',
      code: '6 位數驗證碼', verify: '驗證',
      lost: '無法使用驗證器？請聯絡 AskLinTax 的 CPA 管理員重設兩步驟驗證。我們不會只憑電子郵件進行重設。',
    },
    clientHome: {
      title: '你已登入',
      body: '安全的客戶入口將在後續階段連接。這裡目前不會顯示任何稅務資料。',
    },
    staffHome: {
      title: '員工驗證完成',
      body: '本次登入已完成兩步驟驗證。員工工具將在後續階段連接。',
      note: '此頁面只反映登入狀態。能否存取任何客戶資料，由入口資料庫決定，而不是由此頁面決定。',
    },
  },
}

module.exports = { STRINGS }
